### ISSUE TITLE
Method has decorator, put the decorator plugin before the classes one.

### ISSUE THREAD

**Issue by khomyakov42** [expo/babel-preset-expo#2]
Decorators do not work. Problem with the order of babel plugins: transform-decorators-legacy (in babel-preset-expo) should be run before  transform-class-properties (in babel-preset-react-native)

**Comment by ide** [comment]
I believe Babel plugins run before presets. We could try `passPerPreset: true` but I'm afraid it might break something. I think we should just document that this doesn't work (decorators are unstable, they're not the actual spec anyway) and if you want to provide a custom babelrc you can and have access to all the source code to figure out what it should look like.

**Comment by ide** [comment]
Closing this since we don't have intent to work on this and just want to clearly communicate that to set expectations.
